// Command fixture emits the cross-language test vector that the TypeScript
// suite verifies. Go mints, TypeScript checks, so a divergence in the canonical
// signing bytes fails a test instead of failing a settlement in front of a
// customer. Regenerate after any change to the assertion contract:
//
//	go run ./cmd/fixture > packages/types/src/__fixtures__/go-minted-assertion.json
package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"log"
	"os"
	"time"

	"github.com/craig-hunt/agentic-attribution/internal/attribution"
)

func main() {
	// A fixed seed keeps the fixture reproducible and keeps real key material
	// out of it. Nothing here signs anything a verifier would trust.
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}

	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	issuedAt := time.Date(2026, 7, 30, 12, 0, 0, 0, time.UTC)

	// The identifiers carry <, >, and & on purpose. Either language
	// reintroducing HTML escaping in the canonical form breaks this fixture,
	// which is the only cheap way to catch that class of drift.
	assertion, err := attribution.NewSigner(priv).Mint(
		"018f4a2b-7c31-7000-8000-abcdef123456",
		"pub_a<1>",
		"prod_x&y",
		"req_m4n5p6",
		450,
		issuedAt,
	)
	if err != nil {
		log.Fatalf("mint fixture assertion: %v", err)
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)

	err = enc.Encode(map[string]any{
		"note":       "Generated by `go run ./cmd/fixture`. The TypeScript suite verifies it. Do not hand edit.",
		"public_key": base64.StdEncoding.EncodeToString(pub),
		"verify_at":  issuedAt.Add(30 * time.Minute).UTC().Format(time.RFC3339),
		"expired_at": issuedAt.Add(2 * time.Hour).UTC().Format(time.RFC3339),
		"assertion":  assertion,
	})
	if err != nil {
		log.Fatalf("encode fixture: %v", err)
	}
}
